apiVersion: v2
name: sam-agent
description: A Helm chart for deploying Solace Agent Mesh agents and gateways
type: application
version: 1.2.2
maintainers:
  - name: Solace
    email: info@solace.com
home: https://solace.com/products/agent-mesh/
