apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sam.fullname" $ }}-agent-deployer-config
  labels:
    {{- include "sam.labels" $ | nindent 4 }}
data:
    HELM_CACHE_HOME: "/tmp"
    ESCAPE_CONFIGURATION_FILE_SINGLE_QUOTE: "true"
    JSON_OBJECT_OUTPUT_FORMAT: "json"
    DEPLOYER_VERSION: {{ .Values.samDeployment.agentDeployer.version | quote }}
    DEPLOYMENT_ENV: "k8s"
    HEALTH_SERVER_ENABLED: "true"
    HEALTH_SERVER_PORT: "8089"
    HEALTH_LIVENESS_PATH: "/healthz"
    HEALTH_READINESS_PATH: "/readyz"
    HEALTH_STARTUP_PATH: "/startup"
    READINESS_CHECK_PERIOD: "5"
    STARTUP_CHECK_PERIOD: "5"
