{{- if and .Values.service.tls.enabled (not .Values.service.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-tls
  annotations:
    {{- include "sam.annotations" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.service.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.service.tls.key | b64enc | quote }}
{{- end }}
