apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-init-credentials
  labels:
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
  S3_BUCKET_NAME: {{ include "sam.s3.bucketName" . | b64enc }}
  CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.s3.connectorSpecBucketName" . | b64enc }}
  S3_ACCESS_KEY: {{ include "sam.s3.accessKey" . | b64enc }}
  S3_SECRET_KEY: {{ include "sam.s3.secretKey" . | b64enc }}
  WEB_UI_GATEWAY_DATABASE_USER: {{ include "sam.database.webuiUser" . | b64enc }}
  WEB_UI_GATEWAY_DATABASE_PASSWORD: {{ include "sam.database.webuiPassword" . | b64enc }}
  WEB_UI_GATEWAY_DATABASE_NAME: {{ include "sam.database.webuiName" . | b64enc }}
  PLATFORM_DATABASE_USER: {{ include "sam.database.platformUser" . | b64enc }}
  PLATFORM_DATABASE_PASSWORD: {{ include "sam.database.platformPassword" . | b64enc }}
  PLATFORM_DATABASE_NAME: {{ include "sam.database.platformName" . | b64enc }}
  ORCHESTRATOR_DATABASE_USER: {{ include "sam.database.orchestratorUser" . | b64enc }}
  ORCHESTRATOR_DATABASE_PASSWORD: {{ include "sam.database.orchestratorPassword" . | b64enc }}
  ORCHESTRATOR_DATABASE_NAME: {{ include "sam.database.orchestratorName" . | b64enc }}