{{- if not .Values.global.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-s3
  labels:
    app.kubernetes.io/service: s3
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
    S3_ENDPOINT_URL: {{ include "sam.s3.endpointUrl" . | b64enc }}
    S3_BUCKET: {{ include "sam.s3.bucketName" . | b64enc }}
    CONNECTOR_SPEC_BUCKET: {{ include "sam.s3.connectorSpecBucketName" . | b64enc }}
    S3_ACCESS_KEY: {{ include "sam.s3.accessKey" . | b64enc }}
    S3_SECRET_KEY: {{ include "sam.s3.secretKey" . | b64enc }}
{{- end }}